/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejak.GUI;
import Ejak.koneksi.Waktu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.*;
/**
 *
 * @author dimasgs
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
    initComponents();
    waktu();
    setLocationRelativeTo(null);
    setTitle("Menu Utama | EZAK ITERA");
    //this.getContentPane().setLayout(new FlowLayout());
    }
    void waktu ()
    {
        try
        {
            Waktu objwaktu = new Waktu();
            //System.out.println ( "bisa mengambil waktu ");
            tanggal.setText(objwaktu.getWaktu());
        }
        catch (Exception e)
        {
            System.out.println ("Gagal ambil waktu"+e);
        }
      ActionListener taskPerformer = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        String nol_jam = "";
        String nol_menit = "";
        String nol_detik = "";
        Date dt = new Date();
        int nilai_jam = dt.getHours();
        int nilai_menit = dt.getMinutes();
        int nilai_detik = dt.getSeconds();
        // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
        if (nilai_jam <= 9) {
          // Tambahkan "0" didepannya
          nol_jam = "0";
        }
        // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
        if (nilai_menit <= 9) {
          // Tambahkan "0" didepannya
          nol_menit = "0";
        }
        // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
        if (nilai_detik <= 9) {
          // Tambahkan "0" didepannya
          nol_detik = "0";
        }
        // Membuat String JAM, MENIT, DETIK
        String jam = nol_jam + Integer.toString(nilai_jam);
        String menit = nol_menit + Integer.toString(nilai_menit);
        String detik = nol_detik + Integer.toString(nilai_detik);
        // Menampilkan pada Layar
        tampil_jam.setText("" + jam + " : " + menit + " : " + detik + "  ");
    }
    };
      new Timer(1000, taskPerformer).start();
    }
    public void tampilUser(String user){
        namauser.setText(user);
        
    }
    public void hakAksesAdmin(){
        mnuPengguna.setEnabled(true);
    }
    
    public void hakAksesUser(){
        mnuPengguna.setEnabled(false);
        jMenuItem9.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namauser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        tampil_jam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuPengguna = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("\n");
        setMinimumSize(new java.awt.Dimension(350, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(namauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 120, 30));

        jLabel2.setFont(new java.awt.Font("Noto Sans Mono CJK JP Regular", 0, 18)); // NOI18N
        jLabel2.setText("Selamat Datang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        tanggal.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        tanggal.setText("Tanggal");
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, 30));

        tampil_jam.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        tampil_jam.setText("Jam");
        getContentPane().add(tampil_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/Menu Utama.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 390));

        jMenuBar1.setBackground(new java.awt.Color(87, 188, 188));
        jMenuBar1.setForeground(new java.awt.Color(87, 188, 188));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(350, 32769));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(350, 90));

        jMenu2.setBackground(new java.awt.Color(254, 254, 254));
        jMenu2.setForeground(new java.awt.Color(254, 254, 254));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/Medium 044.png"))); // NOI18N
        jMenu2.setText("Menu");
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem1.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/ExitToolbar.png"))); // NOI18N
        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/Exit.png"))); // NOI18N
        jMenuItem2.setText("Keluar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(254, 254, 254));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/bayar.png"))); // NOI18N
        jMenu3.setText("Transaksi");
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem7.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/buku.png"))); // NOI18N
        jMenuItem7.setText("Pembayaran");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(254, 254, 254));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/Ganti Password.png"))); // NOI18N
        jMenu4.setText("Utility");
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnuPengguna.setForeground(new java.awt.Color(1, 1, 1));
        mnuPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/anggota.png"))); // NOI18N
        mnuPengguna.setText("Data Pengguna");
        mnuPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPenggunaActionPerformed(evt);
            }
        });
        jMenu4.add(mnuPengguna);

        jMenuItem9.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/Medium 003.png"))); // NOI18N
        jMenuItem9.setText("Zakater");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem6.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem6.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/Addnew toolbar.png"))); // NOI18N
        jMenuItem6.setText("Daftar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu1.setForeground(new java.awt.Color(254, 254, 254));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/info-icon-14.png"))); // NOI18N
        jMenu1.setText("Info");
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem4.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/detail.png"))); // NOI18N
        jMenuItem4.setText("Info Zakat");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/About.png"))); // NOI18N
        jMenuItem5.setText("Tentang Kami");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPenggunaActionPerformed
        // TODO add your handling code here:
        Pengguna a = new Pengguna();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuPenggunaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:      
        login a = new login();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Pembayaran tb=new Pembayaran();
        tb.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        InfoZakat mb=new InfoZakat();
        mb.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here
        Daftar a = new Daftar();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        Zakater a = new Zakater();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new MenuUtama().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mnuPengguna;
    private javax.swing.JLabel namauser;
    private javax.swing.JLabel tampil_jam;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
