package Ejak.GUI;

import Ejak.Method.BayarControl;
import Ejak.Method.DetailBayarControl;
import Ejak.Method.ZakatControl;
import Ejak.koneksi.Waktu;
import Ejak.koneksi.koneksi;
import com.mysql.jdbc.Connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dimasgs
 */
public class Pembayaran extends javax.swing.JFrame {
private Connection koneksi;
private final koneksi db = new koneksi();
int jenis = 0;
private DefaultTableModel model;
DetailBayarControl dbc=new DetailBayarControl();
BayarControl bc=new BayarControl();
ZakatControl brgc=new ZakatControl();

    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        waktu();
        setLocationRelativeTo(null);
        setTitle("Pembayaran | EZAK ITERA");
        jmlkmbng.setVisible(false);
        jmlkmbngg.setVisible(false);
        jmlsapi1.setVisible(false);
        jmlsapii1.setVisible(false);
        jmlemas.setVisible(false);
        jmlemas1.setVisible(false);
        jmlklrga.setVisible(false);
        txtJmlklrga.setVisible(false);
        jmlpenghasilan.setVisible(false);
        jmlpnghasilan.setVisible(false);
        jmlperak.setVisible(false);
        jmlperak1.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Menu Pembayaran | EZAK ITERA");
        
    }
    void waktu ()
    {
        try
        {
            Waktu objwaktu = new Waktu();
            //System.out.println ( "bisa mengambil waktu ");
            tanggal.setText(objwaktu.getWaktu());
        }
        catch (Exception e)
        {
            System.out.println ("Gagal ambil waktu"+e);
        }
      ActionListener taskPerformer = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        String nol_jam = "";
        String nol_menit = "";
        String nol_detik = "";
        Date dt = new Date();
        int nilai_jam = dt.getHours();
        int nilai_menit = dt.getMinutes();
        int nilai_detik = dt.getSeconds();
        // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
        if (nilai_jam <= 9) {
          // Tambahkan "0" didepannya
          nol_jam = "0";
        }
        // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
        if (nilai_menit <= 9) {
          // Tambahkan "0" didepannya
          nol_menit = "0";
        }
        // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
        if (nilai_detik <= 9) {
          // Tambahkan "0" didepannya
          nol_detik = "0";
        }
        // Membuat String JAM, MENIT, DETIK
        String jam = nol_jam + Integer.toString(nilai_jam);
        String menit = nol_menit + Integer.toString(nilai_menit);
        String detik = nol_detik + Integer.toString(nilai_detik);
        // Menampilkan pada Layar
        tampil_jam.setText("" + jam + " : " + menit + " : " + detik + "  ");
    }
    };
      new Timer(1000, taskPerformer).start();
    }

     private void bersih(){
        txtPembayar.setText(null);
        txtHarga.setText(null);
        txtJmlklrga.setText(null);
    }

    private void siapIsi(boolean a){
        txtPembayar.setEnabled(a);
        txtHarga.setEnabled(a);
        txtJmlklrga.setEnabled(a);
    }

    private void tombolNormal(){
        btnHitung.setEnabled(true);    
    }

    private void buatTabelBayar(){
        model=new DefaultTableModel();
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
    }


    private void buatTabelBarang(){
        model=new DefaultTableModel();
        model.addColumn("Nama Zakat");
        model.addColumn("Harga");
        tblMasterZakat.setModel(model);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmBarang = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMasterZakat = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCariBrg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        tampil_jam = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPembayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        harga = new javax.swing.JLabel();
        txtJmlklrga = new javax.swing.JTextField();
        jmlklrga = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fitrah = new javax.swing.JRadioButton();
        emas = new javax.swing.JRadioButton();
        perak = new javax.swing.JRadioButton();
        sapi = new javax.swing.JRadioButton();
        kambing = new javax.swing.JRadioButton();
        profesi = new javax.swing.JRadioButton();
        jmlkmbng = new javax.swing.JLabel();
        jmlkmbngg = new javax.swing.JTextField();
        jmlsapii1 = new javax.swing.JTextField();
        jmlsapi1 = new javax.swing.JLabel();
        jmlemas = new javax.swing.JLabel();
        jmlemas1 = new javax.swing.JTextField();
        jmlperak = new javax.swing.JLabel();
        jmlperak1 = new javax.swing.JTextField();
        jmlpnghasilan = new javax.swing.JLabel();
        jmlpenghasilan = new javax.swing.JTextField();
        btnHitung = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jenis_zakat = new javax.swing.JLabel();

        frmBarang.setTitle("Master Data Barang");

        tblMasterZakat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMasterZakat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMasterZakatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMasterZakat);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Data Barang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ketikan Kriteria Pencarian [ENTER]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtCariBrg.setText("jTextField1");
        txtCariBrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariBrgKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(txtCariBrg, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frmBarangLayout = new javax.swing.GroupLayout(frmBarang.getContentPane());
        frmBarang.getContentPane().setLayout(frmBarangLayout);
        frmBarangLayout.setHorizontalGroup(
            frmBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frmBarangLayout.setVerticalGroup(
            frmBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmBarangLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(1, 1, 1));
        setMinimumSize(new java.awt.Dimension(350, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(87, 188, 188));
        jPanel1.setForeground(new java.awt.Color(87, 188, 188));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Pembayaran");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        tanggal.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        tanggal.setText("Tanggal");
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        tampil_jam.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        tampil_jam.setText("Jam");
        jPanel1.add(tampil_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Pembayar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 30));
        getContentPane().add(txtPembayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 150, -1));

        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Nama Zakat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, -1));

        harga.setForeground(new java.awt.Color(1, 1, 1));
        harga.setText("Harga");
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        txtJmlklrga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlklrgaActionPerformed(evt);
            }
        });
        txtJmlklrga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJmlklrgaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJmlklrgaKeyPressed(evt);
            }
        });
        getContentPane().add(txtJmlklrga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 80, -1));

        jmlklrga.setForeground(new java.awt.Color(1, 1, 1));
        jmlklrga.setText("Jumlah Anggota Keluarga");
        getContentPane().add(jmlklrga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));

        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("Total Zakat yang harus dikeluarkan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, 20));

        buttonGroup1.add(fitrah);
        fitrah.setForeground(new java.awt.Color(1, 1, 1));
        fitrah.setText("Zakat Fitrah");
        fitrah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitrahActionPerformed(evt);
            }
        });
        getContentPane().add(fitrah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        buttonGroup1.add(emas);
        emas.setForeground(new java.awt.Color(1, 1, 1));
        emas.setText("Zakat Emas");
        emas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emasActionPerformed(evt);
            }
        });
        getContentPane().add(emas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        buttonGroup1.add(perak);
        perak.setForeground(new java.awt.Color(1, 1, 1));
        perak.setText("Zakat Perak");
        perak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perakActionPerformed(evt);
            }
        });
        getContentPane().add(perak, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        buttonGroup1.add(sapi);
        sapi.setForeground(new java.awt.Color(1, 1, 1));
        sapi.setText("Zakat Sapi");
        sapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapiActionPerformed(evt);
            }
        });
        getContentPane().add(sapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        buttonGroup1.add(kambing);
        kambing.setForeground(new java.awt.Color(1, 1, 1));
        kambing.setText("Zakat Kambing");
        kambing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kambingActionPerformed(evt);
            }
        });
        getContentPane().add(kambing, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        buttonGroup1.add(profesi);
        profesi.setForeground(new java.awt.Color(1, 1, 1));
        profesi.setText("Zakat Profesi");
        profesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesiActionPerformed(evt);
            }
        });
        getContentPane().add(profesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jmlkmbng.setForeground(new java.awt.Color(1, 1, 1));
        jmlkmbng.setText("Jumlah Kambing");
        getContentPane().add(jmlkmbng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));
        getContentPane().add(jmlkmbngg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 90, 30));
        getContentPane().add(jmlsapii1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 90, 30));

        jmlsapi1.setForeground(new java.awt.Color(1, 1, 1));
        jmlsapi1.setText("Jumlah Sapi");
        getContentPane().add(jmlsapi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));

        jmlemas.setForeground(new java.awt.Color(1, 1, 1));
        jmlemas.setText("Jumlah Emas");
        getContentPane().add(jmlemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));
        getContentPane().add(jmlemas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 100, -1));

        jmlperak.setForeground(new java.awt.Color(1, 1, 1));
        jmlperak.setText("Jumlah Perak");
        getContentPane().add(jmlperak, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));
        getContentPane().add(jmlperak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 100, -1));

        jmlpnghasilan.setForeground(new java.awt.Color(1, 1, 1));
        jmlpnghasilan.setText("Jumlah Penghasilan");
        getContentPane().add(jmlpnghasilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));
        getContentPane().add(jmlpenghasilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 100, -1));

        btnHitung.setForeground(new java.awt.Color(1, 1, 1));
        btnHitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/bayar.png"))); // NOI18N
        btnHitung.setText("Bayar");
        btnHitung.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHitung.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHitungMouseClicked(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Rp. ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        back.setForeground(new java.awt.Color(1, 1, 1));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/User-Interface-Logout-icon.png"))); // NOI18N
        back.setText("Kembali");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejak/gambar/pembayaran2.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 50, 350, 430));

        jenis_zakat.setText("jLabel7");
        getContentPane().add(jenis_zakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJmlklrgaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlklrgaKeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtJmlklrgaKeyTyped

    private void txtJmlklrgaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlklrgaKeyPressed

    }//GEN-LAST:event_txtJmlklrgaKeyPressed

    private void txtJmlklrgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlklrgaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlklrgaActionPerformed

    private void tblMasterZakatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMasterZakatMouseClicked
        // TODO add your handling code here:
        int baris = tblMasterZakat.getSelectedRow();
        txtHarga.setText(tblMasterZakat.getModel().getValueAt(baris, 1).toString());
        txtJmlklrga.requestFocus();
        frmBarang.setVisible(false);
    }//GEN-LAST:event_tblMasterZakatMouseClicked

    private void txtCariBrgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariBrgKeyPressed

    }//GEN-LAST:event_txtCariBrgKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void fitrahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitrahActionPerformed
        // TODO add your handling code here:
        jenis = 1;
        harga.setVisible(true);
        txtHarga.setVisible(true);
        harga.setText("Harga Beras Perkilogram");
        txtHarga.setText("Rp. 10000");        
        jmlpenghasilan.setVisible(false);
        jmlpnghasilan.setVisible(false);
        jmlkmbng.setVisible(false);
        jmlkmbngg.setVisible(false);
        jmlsapi1.setVisible(false);
        jmlsapii1.setVisible(false);
        jmlperak.setVisible(false);
        jmlperak1.setVisible(false);
        jmlemas.setVisible(false);
        jmlemas1.setVisible(false);
        jmlklrga.setVisible(true);
        txtJmlklrga.setVisible(true);        
    }//GEN-LAST:event_fitrahActionPerformed

    private void emasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emasActionPerformed
        // TODO add your handling code here:
        jenis = 2;
        harga.setVisible(true);
        txtHarga.setVisible(true);
        harga.setText("Harga Emas Pergram");
        txtHarga.setText("Rp. 600000");
        jmlpenghasilan.setVisible(false);
        jmlpnghasilan.setVisible(false);
        jmlkmbng.setVisible(false);
        jmlkmbngg.setVisible(false);
        jmlsapi1.setVisible(false);
        jmlsapii1.setVisible(false);
        jmlperak.setVisible(false);
        jmlperak1.setVisible(false);
        jmlemas.setVisible(true);
        jmlemas1.setVisible(true);
        jmlklrga.setVisible(false);
        txtJmlklrga.setVisible(false);
    }//GEN-LAST:event_emasActionPerformed

    private void perakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perakActionPerformed
        // TODO add your handling code here:
        jenis = 3;
        harga.setVisible(true);
        txtHarga.setVisible(true);
        harga.setText("Harga Perak Pergram");
        txtHarga.setText("Rp. 200000");
        jmlpenghasilan.setVisible(false);
        jmlpnghasilan.setVisible(false);
        jmlkmbng.setVisible(false);
        jmlkmbngg.setVisible(false);
        jmlsapi1.setVisible(false);
        jmlsapii1.setVisible(false);
        jmlperak.setVisible(true);
        jmlperak1.setVisible(true);
        jmlemas.setVisible(false);
        jmlemas1.setVisible(false);
        jmlklrga.setVisible(false);
        txtJmlklrga.setVisible(false);
    }//GEN-LAST:event_perakActionPerformed

    private void sapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapiActionPerformed
        // TODO add your handling code here:
        jenis = 4;
        harga.setVisible(true);
        txtHarga.setVisible(true);
        harga.setText("Harga Sapi Perekor");
        txtHarga.setText("Rp. 10000000");
        jmlpenghasilan.setVisible(false);
        jmlpnghasilan.setVisible(false);
        jmlkmbng.setVisible(false);
        jmlkmbngg.setVisible(false);
        jmlsapi1.setVisible(true);
        jmlsapii1.setVisible(true);
        jmlperak.setVisible(false);
        jmlperak1.setVisible(false);
        jmlemas.setVisible(false);
        jmlemas1.setVisible(false);
        jmlklrga.setVisible(false);
        txtJmlklrga.setVisible(false);       
    }//GEN-LAST:event_sapiActionPerformed

    private void kambingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kambingActionPerformed
        // TODO add your handling code here:
        jenis = 5;
        harga.setVisible(true);
        txtHarga.setVisible(true);
        harga.setText("Harga Kambing Perekor");
        txtHarga.setText("Rp. 3000000");
        jmlpenghasilan.setVisible(false);
        jmlpnghasilan.setVisible(false);
        jmlkmbng.setVisible(true);
        jmlkmbngg.setVisible(true);
        jmlsapi1.setVisible(false);
        jmlsapii1.setVisible(false);
        jmlperak.setVisible(false);
        jmlperak1.setVisible(false);
        jmlemas.setVisible(false);
        jmlemas1.setVisible(false);
        jmlklrga.setVisible(false);
        txtJmlklrga.setVisible(false);        
    }//GEN-LAST:event_kambingActionPerformed

    private void profesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesiActionPerformed
        // TODO add your handling code here:
        jenis = 6;
        harga.setVisible(false);
        txtHarga.setVisible(false);
        jmlpenghasilan.setVisible(true);
        jmlpnghasilan.setVisible(true);
        jmlkmbng.setVisible(false);
        jmlkmbngg.setVisible(false);
        jmlsapi1.setVisible(false);
        jmlsapii1.setVisible(false);
        jmlperak.setVisible(false);
        jmlperak1.setVisible(false);
        jmlemas.setVisible(false);
        jmlemas1.setVisible(false);
        jmlklrga.setVisible(false);
        txtJmlklrga.setVisible(false);
    }//GEN-LAST:event_profesiActionPerformed

    private void btnHitungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseClicked
        // TODO add your handling code here:
        if(jenis == 1){//fitrah
        int a,b;
        double c;
        double x=2.5;
        a = Integer.parseInt(txtJmlklrga.getText());
        c = ((10000*x)*a);
        //System.out.println(""+c);
        jLabel9.setText(""+String.valueOf(c));
        jenis_zakat.setText("Fitrah");
        db.dbConnection(); 
       try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" + txtPembayar.getText()+"','" + jLabel9.getText()+"','"+jenis_zakat.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        } if (jenis ==2){//emas
            db.dbConnection(); 
        int a;
        String s;
        double c;
        double x=2.5;
        a = Integer.parseInt(jmlemas1.getText());
        c = (x*(a*600000))/100;
        jLabel9.setText(""+String.valueOf(c));
        jenis_zakat.setText("Emas");
        if (a<90){
            JOptionPane.showMessageDialog(null,"Anda belum wajib membayar zakat Emas");
        } else {
           try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"','"+jenis_zakat.getText()+"')";
            st.executeUpdate(sql);
        
         } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        } if (jenis==3){//perak
                int a,b;
        double c;
        double x=2.5;
        a = Integer.parseInt(jmlperak1.getText());
        c = (x*(a*200000))/100;
        
        db.dbConnection(); 
        if (a < 600){
        JOptionPane.showMessageDialog(null,"Anda Belum Wajib Membayar Zakat");
        } else if (a >= 600){
        jLabel9.setText(""+String.valueOf(c));
        jenis_zakat.setText("Perak");
         try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"','"+jenis_zakat.getText()+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
         } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        } if (jenis == 4){//sapi
           int a;
           int c;
           a = Integer.parseInt(jmlsapii1.getText());
           if (a<30){
               JOptionPane.showMessageDialog(null,"Nisab belum terpebuhi");
           } else if (a<59){
           c = 10000000;
               jLabel9.setText(""+String.valueOf(c));
               jenis_zakat.setText("Sapi");
                   try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"','"+jenis_zakat.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
           } else if (a<69){
            c = 2*10000000;
               jLabel9.setText(""+String.valueOf(c));
                    try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
           } else if (a<79){
            c = 3*10000000;
               jLabel9.setText(""+String.valueOf(c));
                    try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
           } else if (a<89){
            c = 4*10000000;
               jLabel9.setText(""+String.valueOf(c));
                    try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
           } else if (a >= 90){
            c = 5 * 10000000;
                  jLabel9.setText(""+String.valueOf(c));
                    try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
        } if (jenis == 5){ //kambing
                    int a;
           int b;
           int c;
           a = Integer.parseInt(jmlkmbngg.getText());
            if (a<40){
             JOptionPane.showMessageDialog(null,"Nisab belum terpenuhi");
            } else if (a<120){
                c = 3000000;
                jLabel9.setText(""+String.valueOf(c));
                jenis_zakat.setText("Kambing");
            try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"','"+jenis_zakat.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            } else if (a<200){
                c = 2*3000000;
                jLabel9.setText(""+String.valueOf(c));
                     try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            } else if (a<300){
                c = 3*3000000;
                jLabel9.setText(""+String.valueOf(c));
                     try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            } else if (a<400) {
                c = 4*3000000;
                jLabel9.setText(""+String.valueOf(c));
                     try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            }
        
        } else if (jenis == 6){//profesi
        int n = 10000;
        int m;
        m = (n*520);
        int a;
        double b;
        double c = 2.5;
        a = Integer.parseInt(jmlpenghasilan.getText());
        if (m<a){
            b = (c*a)/100;
            jLabel9.setText(""+String.valueOf(b));
            jenis_zakat.setText("Profesi");
        } else {
            JOptionPane.showMessageDialog(null, "Nisab Tidak Mencukupi");
        }
        db.dbConnection(); 
       try{
            Statement st = db.getConnection().createStatement();
            String sql = "INSERT INTO bayar VALUES ('" +txtPembayar.getText()+"','"+jLabel9.getText()+"','"+jenis_zakat.getText()+"')";
            st.executeUpdate(sql);
            
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        }

    }//GEN-LAST:event_btnHitungMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        MenuUtama a = new MenuUtama();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel btnHitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton emas;
    private javax.swing.JRadioButton fitrah;
    private javax.swing.JDialog frmBarang;
    private javax.swing.JLabel harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jenis_zakat;
    private javax.swing.JLabel jmlemas;
    private javax.swing.JTextField jmlemas1;
    private javax.swing.JLabel jmlklrga;
    private javax.swing.JLabel jmlkmbng;
    private javax.swing.JTextField jmlkmbngg;
    private javax.swing.JTextField jmlpenghasilan;
    private javax.swing.JLabel jmlperak;
    private javax.swing.JTextField jmlperak1;
    private javax.swing.JLabel jmlpnghasilan;
    private javax.swing.JLabel jmlsapi1;
    private javax.swing.JTextField jmlsapii1;
    private javax.swing.JRadioButton kambing;
    private javax.swing.JRadioButton perak;
    private javax.swing.JRadioButton profesi;
    private javax.swing.JRadioButton sapi;
    private javax.swing.JLabel tampil_jam;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTable tblMasterZakat;
    private javax.swing.JTextField txtCariBrg;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJmlklrga;
    private javax.swing.JTextField txtPembayar;
    // End of variables declaration//GEN-END:variables
}
